import random as rd
a, b = eval(input(f"enter the 1st and last limit of random no = "))
        # in eval() entered  no.s separated by comma(,) only 
        # set the limit
r = rd.randint(a, b) 
    # store random value generated by pc
print(r)